---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: yes
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/iTechyTony/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Repositories/dotfiles
dotfiles_files:
  - .ctags
  - .spacemacs
  - .spacemacs.d
  - .gitconfig
  - .gitignore_global
  - .hushlogin
  - .offlineimaprc
  - .php-cs-fixer
  - .tmux.conf
  - .zprofile
  - .zshrc


homebrew_installed_packages:
  - composer
  - git
  - go
  - httpie
  - ledger
  - mu
  - node@10
  - nvm
  - offlineimap
  - openssl
  - php@7.2
  - readline
  - sqlite
  - ssh-copy-id
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - dbeaver-community
  - docker
  - dropbox
  - firefox
  - google-chrome
  - growlnotify
  - mactex
  - sequel-pro
  - slack
  - transmit
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: laravel/installer
    state: present
  #   version: "~> 1.15.1" # default: N/A
  - name: laravel/valet
    state: present
  - name: laravel/lumen-installer
    state: present
  - name: phpunit/phpunit
    state: present
  - name: phing/phing
    state: present
  - name: phpmd/phpmd
    state: present
  - name: squizlabs/php_codesniffer
    state: present
  - name: phpstan/phpstan
    state: present
  # - name: phpactor/phpactor
  #   state: present


gem_packages: []
  # - name: bundle
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: webpack
    state: present # present/absent/latest, default: present
    # version: "~> 1.15.1" # default: N/A
  - name: bower
    state: present
  - name: gulp
    state: present
  - name: grunt
    state: present
  - name: tern
    state: present

pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
