---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/iTechyTony/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Repositories/dotfiles
dotfiles_files:
  - .aliases.zsh
  - .ctags
  - .doom.d
  - .gitconfig
  - .gitignore_global
  - .hushlogin
  - .hyper.js
  - .offlineimaprc
  - .php-cs-fixer
  - .tmux.conf
  - .zshenv
  - .zshrc


homebrew_installed_packages:
  - ag
  - composer
  - coreutils
  - editorconfig
  - fd
  - git
  - global
  - glslang
  - gnu-tar
  - go
  - httpie
  - lastpass-cli
  - ledger
  - libvterm
  - markdown
  - mu
  - node@10
  - nvm
  - offlineimap
  - openssl
  - pandoc
  - php@7.2
  - proselint
  - pyenv
  - readline
  - ripgrep
  - sbcl
  - shellcheck
  - sqlite
  - ssh-copy-id
  - tmux
  - wget
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - appcleaner
  - chromedriver
  - dbeaver-community
  - docker
  - dropbox
  - emacs
  - firefox
  - font-office-code-pro
  - google-chrome
  - hyper
  - marked
  - sequel-pro
  - slack
  - spectacle
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: laravel/installer
    state: present
  - name: laravel/valet
    state: present
  - name: laravel/lumen-installer
    state: present
  - name: phpunit/phpunit
    state: present
  - name: phing/phing
    state: present
  - name: phpmd/phpmd
    state: present
  - name: squizlabs/php_codesniffer
    state: present
  - name: phpstan/phpstan
    state: present
  - name: psy/psysh
    state: present
  - name: laravel/envoy
    state: present
  - name: friendsofphp/php-cs-fixer
    state: present


gem_packages:
  # - name: bundle
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
  - name: mdl
    state: present
npm_packages:
  - name: webpack
    state: present # present/absent/latest, default: present
    # version: "~> 1.15.1" # default: N/A
  - name: bower
    state: present
  - name: gulp
    state: present
  - name: grunt
    state: present
  - name: tern
    state: present
  - name: vmd
    state: present
  - name: js-beautify
    state: present
  - name: ember-cli
    state: present
  - name: markdownlint
    state: present
  - name: stylelint
    state: present
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
