---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/iTechyTony/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Repositories/dotfiles
dotfiles_files:
  - .ctags
  - .emacs.d
  - .gitconfig
  - .gitignore_global
  - .hushlogin
  - .offlineimaprc
  - .php-cs-fixer
  - .tmux.conf
  - .zprofile
  - .zshrc


homebrew_installed_packages:
  - git
  - httpie
  - sqlite
  - node
  - nvm
  - php@7.2
  - ssh-copy-id
  - readline
  - openssl
  - wget
  - ledger
  - mu
  - composer
  - node

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - sequel-pro
  - slack
  - transmit
  - vagrant
  - mactex

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: laravel/installer
  - name: laravel/valet
  - name: laravel/lumen-installer
  - name: phpunit/phpunit
  - name: phing/phing
  - name: phpmd/phpmd
  - name: squizlabs/php_codesniffer
  - name: phpstan/phpstan


gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
