---
- hosts: all
  connection: local
  become: true
  vars_files:
    - default.config.yml
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
  roles:
  - kewlfft.aur
  tasks:
    - include: tasks/install-pacman-packages.yml
      tags: ['install-pacman-packages']
    - include: tasks/install-aur-packages.yml
      tags: ['install-aur-packages']
    - include: tasks/extra-packages.yml
      tags: ['extra-packages']
    - include: tasks/pass-repo-clonning.yml
      tags: ['pass']
