- name: Package Installation - Update Pacman package cache
  pacman:
    update_cache: true
  changed_when: false

- name: Package Installation - Window Manager Tools
  package:
    name: [
        'bspwm',
        'compton',
        'manjaro-pulse',
        'nitrogen',
        'pavucontrol',
        'playerctl',
        'polybar',
        'pulseaudio',
        'pulseaudio-alsa',
        'pulseaudio-bluetooth',
        'pulseaudio-equalizer',
        'rofi',
        'sxhkd',
    ]
    state: present

- name: Package Installation - Development Tools
  package:
    name: [
        'aspell',
        'aspell-en',
        'binutils',
        'cmake',
        'composer',
        'dbeaver',
        'docker',
        'docker-compose',
        'editorconfig-core-c',
        'emacs',
        'fish',
        'gnome-terminal',
        'htop',
        'languagetool',
        'ledger',
        'npm',
        'offlineimap',
        'pandoc',
        'php',
        'texlive-bin',
        'vagrant',
    ]
    state: present

- name: Package Installation - Media
  package:
    name: [
        'flameshot',
        'imagemagick'
    ]
    state: present

- name: Package Installation - File Manager
  package:
    name: [
        'pcmanfm',
    ]
    state: present
