- name: Package Installation - Update Pacman package cache
  pacman:
    update_cache: true
  changed_when: false

- name: Package Installation - Window Manager Tools
  package:
    name: [
        'compton',
        'manjaro-pulse',
        'polybar',
        'xorg-xkill', # force quit apps
    ]
    state: present

- name: Package Installation - BSPWM Window Manager
  package:
    name: [
        'bspwm',
    ]
    state: present

- name: Package Installation - Keyboard Daemon
  package:
    name: [
        'sxhkd',
    ]
    state: present

- name: Package Installation - Sound Tools
  package:
    name: [
        'pavucontrol',
        'playerctl',
        'pulseaudio',
        'pulseaudio-alsa',
        'pulseaudio-bluetooth',
        'pulseaudio-equalizer',
    ]
    state: present

- name: Package Installation - Wallpaper Manager
  package:
    name: [
        'nitrogen',
    ]
    state: present

- name: Package Installation - Network Manager Tools
  package:
    name: [
      'networkmanager',
      'network-manager-applet',
      'nm-connection-editor',
    ]
    state: present

- name: Package Installation - Power Manager
  package:
    name: [
      'xfce4-power-manager',
    ]
    state: present

- name: Package Installation - Development Tools
  package:
    name: [
        'aspell',
        'aspell-en',
        'binutils',
        'cmake',
        'composer',
        'dbeaver',
        'docker',
        'docker-compose',
        'editorconfig-core-c',
        'emacs',
        'fish',
        'gnome-terminal',
        'htop',
        'languagetool',
        'ledger',
        'npm',
        'offlineimap',
        'pandoc',
        'texlive-bin',
        'vagrant',
        'ripgrep',
        'dnsutils',
    ]
    state: present

- name: Package Installation - PHP
  package:
    name: [
        'php',
        'php-gd',
        'xdebug',
    ]
    state: present

- name: Package Installation - Mysql
  package:
    name: [
        'mysql',
    ]
    state: present

- name: Package Installation - Media
  package:
    name: [
        'flameshot',
        'imagemagick'
    ]
    state: present

- name: Package Installation - Web Browser
  package:
    name: [
        'qutebrowser',
        'surfraw',
    ]
    state: present

- name: Package Installation - File Manager
  package:
    name: [
        'pcmanfm',
    ]
    state: present

- name: Package Installation - Notification
  package:
    name: [
        'dunst',
    ]
    state: present

- name: Package Installation - Application Launcher Rofi
  package:
    name: [
        'rofi',
        'rofi-pass',
        'rofi-calc',
    ]
    state: present

- name: Package Installation - Keyboard and Mouse Tools
  package:
    name: [
        'xcape',
        'xorg-xsetroot',
        'screenkey',
    ]
    state: present

- name: Package Installation - Syncthing File Sync
  package:
    name: [
        'syncthing',
    ]
    state: present
