- name: Package Installation - Update Pacman package cache
  pacman:
    update_cache: true
  changed_when: false

- name: Package Installation - Window Manager Tools
  package:
    name: [
        'i3',
        'i3lock',
        'compton',
        'manjaro-pulse',
        'nitrogen',
        'pavucontrol',
        'playerctl',
        'polybar',
        'pulseaudio',
        'pulseaudio-alsa',
        'pulseaudio-bluetooth',
        'pulseaudio-equalizer',
        'rofi',
    ]
    state: present

- name: Package Installation - Development Tools
  package:
    name: [
        'aspell',
        'aspell-en',
        'binutils',
        'cmake',
        'composer',
        'dbeaver',
        'docker',
        'docker-compose',
        'editorconfig-core-c',
        'emacs',
        'fish',
        'gnome-terminal',
        'htop',
        'languagetool',
        'ledger',
        'npm',
        'offlineimap',
        'pandoc',
        'texlive-bin',
        'vagrant',
        'ripgrep',
        'dnsutils',
    ]
    state: present

- name: Package Installation - PHP
  package:
    name: [
        'php',
        'php-gd',
    ]
    state: present

- name: Package Installation - Mysql
  package:
    name: [
        'mysql',
    ]
    state: present

- name: Package Installation - Media
  package:
    name: [
        'flameshot',
        'imagemagick'
    ]
    state: present

- name: Package Installation - Web Browser
  package:
    name: [
        'qutebrowser',
    ]
    state: present

- name: Package Installation - File Manager
  package:
    name: [
        'pcmanfm',
    ]
    state: present

- name: Package Installation - Keyboard and Mouse Tools
  package:
    name: [
        'xcape',
        'xorg-xsetroot',
        'screenkey',
    ]
    state: present
