- name: Package Installation - Update Pacman package cache
  pacman:
    update_cache: true
  changed_when: false

# - name: Install mpc music player
#   package:
#     name: [
#         'mpc',
#     ]
#     state: present

# - name: Install cmatrix
#   package:
#     name: [
#         'cmatrix',
#     ]
#     state: present

# - name: Install caffeine
#   package:
#     name: [
#         'caffeine',
#     ]
#     state: present

# - name: Package Installation - Keyboard and Mouse Tools
#   package:
#     name: [
#         'xcape',
#         'xorg-xsetroot',
#         'screenkey',
#     ]
#     state: present

# - name: Install sysstat for cpu info
#   package:
#     name: [
#         'sysstat',
#     ]
#     state: present
