homebrew_installed_packages:
  - Schniz/tap/fnm
  - ag
  - automake
  - cmake
  - composer
  - coreutils
  - editorconfig
  - fd
  - git
  - git-flow
  - global
  - glslang
  - gnu-tar
  - go
  - groff
  - gs
  - gtypist
  - httpie
  - ledger
  - libvterm
  - markdown
  - mu
  - offlineimap
  - openssl
  - pandoc
  - pass
  - php
  - poppler
  - proselint
  - pyenv
  - readline
  - ripgrep
  - sbcl
  - shellcheck
  - sqlite
  - ssh-copy-id
  - tmux
  - trash
  - wget
  - zsh
  - languagetool
  - speedtest

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-drivers
  - railwaycat/emacsmacport
  - teamookia/speedtest

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alfred
  - appcleaner
  - chromedriver
  - docker
  - dropbox
  - emacs-mac
  - firefox
  - font-fira-code
  - google-backup-and-sync
  - google-chrome
  - growlnotify
  - hyper
  - insomnia
  - karabiner-elements
  - logitech-options
  - mactex
  - querious
  - skype
  - slack
  - spectacle
  - spotify
  - stoplight-studio
  - tableplus
  - vagrant
  - whatsapp
  - wkhtmltopdf
  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"
