- name: Install php
  package:
    name: php
    state: present
  tags: php

- name: Install php-gd
  package:
    name: php-gd
    state: present
  tags: php

- name: Install xdebug for php
  package:
    name: xdebug
    state: present
  tags: php

- name: Install composer
  package:
    name: composer
    state: present
  tags: php

- name: Laravel valet requirement - install jq
  package:
    name: jq
    state: present
  tags: php

- name: Laravel valet - install xsel
  package:
    name: xsel
    state: present
  tags: php

- name: Laravel valet - install nss
  package:
    name: nss
    state: present
  tags: php

- name: Install php
  package:
    name: php-odbc
    state: present
  tags: php

- name: Install php-pear
  aur:
    use: yay
    name: php-pear
  become: yes
  become_user: "{{username}}"
  tags: php

- name: PHP configuration file
  template:
    src: php.ini.j2
    dest: /etc/php/php.ini
  tags: php

- name: Install php-mongodb
  package:
    name: php-mongodb
    state: present
  tags: php
