- name: Install surfraw
  package:
    name: surfraw
    state: present

- name: Install qutebrowser
  package:
    name: qutebrowser
    state: present

- name: Install chromium
  aur:
    name: chromium
  become: yes
  become_user: "{{username}}"

- name: Install google chrome
  aur:
    name: google-chrome
  become: yes
  become_user: "{{username}}"

- name: Install brave browser
  package:
    name: brave
    state: present

- name: Install browserpass
  aur:
    name: browserpass
  become: yes
  become_user: "{{username}}"

- name: Install browserpass-chromium
  aur:
    name: browserpass-chromium
  become: yes
  become_user: "{{username}}"

- name: Install browserpass-chrome
  aur:
    name: browserpass-chrome
  become: yes
  become_user: "{{username}}"
