- name: Install skype for linux
  aur:
    use: yay
    name: skypeforlinux-stable-bin
  become: yes
  become_user: "{{username}}"

- name: Install slack desktop client
  aur:
    use: yay
    name: slack-desktop
  become: yes
  become_user: "{{username}}"

- name: Install Whatsapp
  aur:
    use: yay
    name: whatsdesk-bin
  become: yes
  become_user: "{{username}}"

- name: Install signal
  package:
    name: signal-desktop
    state: present

- name: Install Microsoft teams
  aur:
    use: yay
    name: teams
  become: yes
  become_user: "{{username}}"
