- name: Install mysql
  package:
    name: mysql
    state: present

- name: Install tableplus
  aur:
    use: yay
    name: tableplus
  become: yes
  become_user: "{{username}}"

- name: Install dbeaver
  aur:
    use: yay
    name: dbeaver
  become: yes
  become_user: "{{username}}"
