- name: Package Installation - Update Pacman package cache
  pacman:
    update_cache: true
  changed_when: false

- name: Install build dev tools
  package:
    name: base-devel
    state: present

- name: Install Development Tools
  package:
    name: [
        'binutils',
        'cmake',
        'htop',
        'npm',
        'vagrant',
        'dnsutils',
    ]
    state: present

- name: Install python2
  package:
    name: python2-pip
    state: present

- name: Install python3
  package:
    name: python-pip
    state: present

- name: Install phpstorm
  aur:
    name: phpstorm
  become: yes
  become_user: tonya
