- name: Package Installation - Update Pacman package cache
  pacman:
    update_cache: true
  changed_when: false

- name: Install build dev tools
  package:
    name: base-devel
    state: present

- name: Install binutils
  package:
    name: binutils
    state: present

- name: Install cmake
  package:
    name: cmake
    state: present

- name: Install htop
  package:
    name: htop
    state: present

- name: Install npm
  package:
    name: npm
    state: present

- name: Install vagrant
  package:
    name: vagrant
    state: present

- name: Install virtualbox
  package:
    name: virtualbox
    state: present

- name: Install dnsutils
  package:
    name: dnsutils
    state: present

- name: Install python2
  package:
    name: python2-pip
    state: present

- name: Install python3
  package:
    name: python-pip
    state: present

- name: Install phpstorm
  aur:
    use: yay
    name: phpstorm
  become: yes
  become_user: "{{username}}"

- name: Install jdk11-openjdk
  package:
    name: jdk11-openjdk
    state: present

- name: Install jdk11-openjdk
  command: archlinux-java set java-11-openjdk
  become: yes
