- name: Install stoplight studio
  aur:
    name: stoplight-studio-appimage
  become: yes
  become_user: tonya

- name: Install postman
  aur:
    name: postman-bin
  become: yes
  become_user: tonya

- name: Install insomnia
  aur:
    name: insomnia
  become: yes
  become_user: tonya
