- name: Install alacritty
  package:
    name: alacritty
    state: present

- name: Install fish shell
  package:
    name: fish
    state: present

- name: Install termite
  package:
    name: termite
    state: present
